#!/bin/bash

# Information de sauvegarde
min_backup=0
max_backup=2

# Affiche l'aide de la commande
function showHelp
{
	echo './backup [ -h ] [ -r <nb> ] [ -e <ssh> ]'
	echo "   -h       : Affiche l'aide"
	echo "   -r <nb>  : Mode restauration avec le numéro de la sauvegarde à restaurer"
	echo "   -e <ssh> : Sauvegarde vers un dossier distant / Restaure depuis un dossier distant"
	exit 0
}

# Récupère la dernière backup
function get_last_backup
{
	# Récupère le dernier dossier de backup (c'est un numero)
	local last=$(ls $destination | grep -e '^[0-9]*$' | sort -n | tail -1)

	if [[ -z $last ]] ; then
		last=-1
	fi
	
	echo $last
}

# Récupère la prochaine backup créée
function get_next_backup
{
	local last=$(get_last_backup) && echo "$((last+1))"
}

# Renomme les backups en cas de dépassement de la backup maximale
function rename_backups
{
	# Si le dernier backup était la sauvegarde max_backup,
	# On supprime le backup n°min_backup et on décale tous les indices de backup
	if [ $last -gt $max_backup ] ; then
		rm -rf "$destination/$min_backup"
		for i in $(seq 1 $last)
		do
			file="$destination/$i"
			echo $file
			if [[ -e $file ]] ; then
				mv $file "$destination/$((i-1))"
			fi
		done
	fi
}

# Effectue une sauvegarde
function save
{
	local source='/home'
	local destination='/srv/backup'
	local last=$(get_next_backup)
	
	if [[ ! -z $ssh_val ]] ; then
		destination="$ssh_val:$destination/$last"
		rsync -e ssh -azvu $source $destination/$last
	else
		rsync -azvu $source $destination/$last
	fi	
	rename_backups
}

# Effectue une restauration
function restore
{
	local source="/srv/backup/$restore_val"
	local destination='/home'
	local ssh_option=''
	
	if [[ ! -z $ssh_val ]] ; then
		source="$uri:$source"
		rsync -e ssh -azvu $source/* $destination
	else
		rsync -azvu $source/* $destination
	fi
}

# Lis les différentes options de la commande
state=1
while getopts "hr:e:" option
do
	case $option in
		h)
			showHelp
			;;
		e)
			ssh_val=$OPTARG
			;;
		r)
			restore_val=$OPTARG
			if [ $restore_val -ge $min_backup ] && [ $restore_val -le $max_backup ] ; then
				state=2
			else
				echo "$restore_val n'est pas une sauvegarde valide."
			fi
			;;
	esac
done

if [ $state == 1 ] ; then
	save
elif [ $state == 2 ] ; then
	restore
fi
